# Generated by Django 5.2.5 on 2025-09-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='dateFabrication',
            new_name='dateFabProd',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='idStatut',
            new_name='idStatus',
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('produit', 'rayon')},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='statut',
            name='libelle',
        ),
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.statut'),
        ),
        migrations.AddField(
            model_name='statut',
            name='libelleStatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_categorie', to='monApp.categorie'),
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='qte',
        ),
        migrations.AddField(
            model_name='contenir',
            name='Qte',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
